// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgN3rQFqn_BFZT-h9QYHC3hjVFmRGZ5Ko',
    appId: '1:180981996983:web:42d85056699a252eb6dc32',
    messagingSenderId: '180981996983',
    projectId: 'plot-twist-8f9fb',
    authDomain: 'plot-twist-8f9fb.firebaseapp.com',
    storageBucket: 'plot-twist-8f9fb.firebasestorage.app',
    measurementId: 'G-QLKDWHBJ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZI5YZa5NOyKmFxFvmJYABKQltJB8CxM',
    appId: '1:180981996983:android:b4b37d0e107898cab6dc32',
    messagingSenderId: '180981996983',
    projectId: 'plot-twist-8f9fb',
    storageBucket: 'plot-twist-8f9fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUofF8JSGeZPBVEl3hsw0r6S2NZoklUI',
    appId: '1:180981996983:ios:f0c8ee4e959cb67fb6dc32',
    messagingSenderId: '180981996983',
    projectId: 'plot-twist-8f9fb',
    storageBucket: 'plot-twist-8f9fb.firebasestorage.app',
    iosBundleId: 'com.example.plotTwist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALUofF8JSGeZPBVEl3hsw0r6S2NZoklUI',
    appId: '1:180981996983:ios:f0c8ee4e959cb67fb6dc32',
    messagingSenderId: '180981996983',
    projectId: 'plot-twist-8f9fb',
    storageBucket: 'plot-twist-8f9fb.firebasestorage.app',
    iosBundleId: 'com.example.plotTwist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgN3rQFqn_BFZT-h9QYHC3hjVFmRGZ5Ko',
    appId: '1:180981996983:web:a7534ef5916f4d9ab6dc32',
    messagingSenderId: '180981996983',
    projectId: 'plot-twist-8f9fb',
    authDomain: 'plot-twist-8f9fb.firebaseapp.com',
    storageBucket: 'plot-twist-8f9fb.firebasestorage.app',
    measurementId: 'G-V10MWGTBLQ',
  );
}
